### ISSUE TITLE
Translate strings into German

### ISSUE THREAD

**Issue by daltonos** [daltonos/dbcdashboard#13]
Convert each string inside the json to German, if necessary.

@David-RHP 
Please do the modification on branch "development", then ask for a pull request to Master.

The strings can be modified directly on this file on the browser:
https://github.com/daltonos/dbcdashboard/blob/development/src/i18n.js

Or they can be done by pulling on your computer.

**Comment by davidrhp** [comment]
@daltonos I added the translations. Please have a look at the comment on line 22.
