### ISSUE TITLE
Set up UI

### ISSUE THREAD

**Issue by daltonos** [daltonos/dbcdashboard#27]
- Install Node.js https://nodejs.org/en/
- Check if NPM is available after installing node.js
   npm -version
- git clone https://github.com/daltonos/dbcdashboard.git
- Go to your cloned folder, do "git status" to check if git is correctly set up.
- Go to master branch (git checkout master)
- At the root folder, run command
   npm start
- Go to http://localhost:8080/ on your browser, and check that the website shows up correctly.

obs: for stopping the UI server, use command "control + C".

**Comment by davidrhp** [comment]
@daltonos Doesn't seem to work (npm version=6.2.0):


 albums-display@1.0.0 start H:\Personal\Python\dbcdashboard
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'H:\Personal\Python\dbcdashboard\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! albums-display@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the albums-display@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david.meyer\AppData\Roaming\npm-cache\_logs\2018-08-24T10_48_44_980Z-debug.log

**Comment by davidrhp** [comment]
has been resolved by executing `npm install` in the root folder before `npm start`
