### ISSUE TITLE
Add links to resources

### ISSUE THREAD

**Issue by daltonos** [daltonos/dbcdashboard#4]
- Show links for each projects, to useful project resources online.
- Links to internal websites.

**Comment by davidrhp** [comment]
@daltonos 
The resource for the dashboard will be:

<some ip>:<some port> + '/projects/dashboard'

**Comment by daltonos** [comment]
what about "/api/projects/dashboard"?

**Comment by davidrhp** [comment]
True, I'll fix it tonight. 

Correct URI:

'api/projects/dashboard'

Also, this will be the only endpoint for this release.
