### ISSUE TITLE
Define which fields to show on each card.

### ISSUE THREAD

**Issue by daltonos** [daltonos/dbcdashboard#6]

**Comment by davidrhp** [comment]
**Fields:**

_values:_
- minimum funding goal as min
- maximum funding goal as max
- amount already in as in
- amount sent out as out

_labels:_
- project name (e.g., Nr. 123 name)  # the id, name etc. would be provided in a single string
- city as Ort (should be close to project name)
- street as Straße (should be close to project name)
- project owner as PM (usually 1 name, might be 2 or 3 while sorting out the responsibilities)
- issuing bank as Bank
- due date (format: dd.mm.yyyy)

Please let me know if thats too much info to display.

**Comment by daltonos** [comment]
It's fine.
It can all be displayed as long as the json server returns it.

**Comment by daltonos** [comment]
@David-RHP  Could you register for me where each of these values come from?

I'd like to know specifically:
- Company
- which DB
- if it is from Wrike or not.

Fields:

- minimum funding goal as min
- maximum funding goal as max
- amount already in as in
- amount sent out as out
- project name
- city
- street
- project owner
- issuing bank
- due date

**Comment by davidrhp** [comment]
W: Wrike
D: internal company database

Fields:

- minimum funding goal as min - W
- maximum funding goal as max - W
- amount already in as in - D
- amount sent out as out - D
- project name - W
- city - W
- street - W
- project owner - W
- issuing bank - W
- due date - W
